Python prints a stack trace when your code throws an exception and is  also referred to as a stack traceback. A stack trace prints all the calls prior to the function that raised an exception. In all cases, the last line of a stack trace prints the most valuable information as here the error gets printed. All information above the thrown error consists of function calls that help you to trace the issue faster.
